version: 3.1.0.{build}

branches:
  only:
    - master

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

build:
  project: src\SteamWebAPI2.sln
  publish_nuget: true
  include_nuget_references: true
  
cache:
  - src\packages -> **\packages.config
  
before_build:
  - cmd: nuget restore src\SteamWebAPI2.sln
  
deploy:
  - provider: NuGet
    api_key:
      secure: vIHuOdB4aYJEqNACb3jjCg3m/qZLqpwYlruu8J0BOiX81lRrmussVEUqiWRBTrRQ
    skip_symbols: false
    artifact: /.*\.nupkg/